# Java Gradle CircleCI 2.0 configuration file
# See: https://circleci.com/docs/2.0/language-java/
version: 2

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build-job:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      # specify the version you desire here
      - image: cimg/openjdk:11.0.13-browsers

    working_directory: ~/repo

    steps:
    # ソースコードをworking_directory(~/repo)に展開
      - checkout
      - run: 
          name: ビルド＆テスト実行(compileJava, compileTestJava, test)
          command: ./gradlew test
  deploy-job:
    docker:
      - image: cimg/base:2022.03
    steps:
      - run:
          name: デプロイ
          command: echo "deploy completed."
workflows:
  version: 2
  test-and-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            # mainブランチへのコミット時のみdeploy-jobを実行
            branches:
              only:
                - main
                - circleci-project-setup
                - tkg_dev1